services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: helvar_service_tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: service-tickets
    build: .
    ports:
      - "8443:8443"
    volumes:
      - ./env.properties:/app/env.properties
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/helvar_service_tickets
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: